---
- name: Create credentials
  hosts: localhost
  gather_facts: false
  vars:
    personal_access_token: 'THcESOLlJNMgbcPwNI067azSRbLU4s'
    machine_credentials:
      username: 'my_user'
      password: 'my_password'

  tasks:
    - name: Create machine credential
      ansible.builtin.uri:
        url: 'https://controller.rh.lab/api/v2/credentials/'
        method: POST
        headers:
          Authorization: 'Bearer {{ personal_access_token }}'
          Content-Type: "application/json"
        body_format: json
        body:
          name: 'my_machine_credential3'
          credential_type: 1
          organization: 1
          inputs: '{{ machine_credentials }}'
        validate_certs: false
        status_code: 201
      register: output

    - debug: var=output
