---
- name: Set variable
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Set stats
      set_stats:
        data:
          data1: 'abcd'

    - name: Set fact
      set_fact:
        data2: 'efgh'
        cacheable: true

    - debug: var=data1
    - debug: var=data2